let screen2 = image.create(scene.screenWidth(), scene.screenHeight())
screen2.fill(15)
scene.setBackgroundImage(screen2)
screen2.drawLine(0, 0, scene.screenWidth(), scene.screenHeight(), 1)
screen2.drawLine(0, scene.screenHeight(), scene.screenWidth(), 0, 1)
screen2.drawRect(scene.screenWidth() / 4 * 1, scene.screenHeight() / 4 * 1, scene.screenWidth() / 4 * 2, scene.screenHeight() / 4 * 2, 1)
screen2.drawRect(scene.screenWidth() / 4 * 1, scene.screenHeight() / 4 * 1, scene.screenWidth() / 4 * 2, scene.screenHeight() / 4 * 2, 1)
screen2.drawRect(scene.screenWidth() / 8 * 3, scene.screenHeight() / 8 * 3, scene.screenWidth() / 8 * 2, scene.screenHeight() / 8 * 2, 1)
screen2.drawRect(scene.screenWidth() / 16 * 7, scene.screenHeight() / 16 * 7, scene.screenWidth() / 16 * 2, scene.screenHeight() / 16 * 2, 1)
